### ISSUE TITLE
actions lead to leaky error in jax

### ISSUE THREAD

**Issue by ioneliabuzatu** [ioneliabuzatu/grn-control#13]
```
/home/ionelia/pycharm-projects/venvs/grn-control/bin/python /home/ionelia/pycharm-projects/grn-control/main.py
simulation num step per trajectories:  3
################################################################################## 0
Traceback (most recent call last):
  File "/home/ionelia/pycharm-projects/grn-control/main.py", line 43, in <module>
    control(sim, 2, 9, len(sim.layers[0]))
  File "/home/ionelia/pycharm-projects/grn-control/main.py", line 23, in control
    loss, grad = jax.value_and_grad(loss_fn)(actions)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/_src/api.py", line 1065, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/_src/api.py", line 2474, in _vjp
    flat_fun, primals_flat, reduce_axes=reduce_axes)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/interpreters/ad.py", line 116, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/interpreters/ad.py", line 103, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 520, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/linear_util.py", line 181, in call_wrapped
    ans = gen.send(ans)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/interpreters/ad.py", line 57, in jvpfun
    del main
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ionelia/pycharm-projects/venvs/grn-control/lib/python3.7/site-packages/jax/core.py", line 792, in new_main
    raise Exception(f'Leaked level {t()}. Leaked tracer(s): {leaked_tracers}.')
jax._src.traceback_util.UnfilteredStackTrace: Exception: Leaked level MainTrace(2,JVPTrace). Leaked tracer(s): [Traced<ConcreteArray([[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]], dtype=float32)>with<JVPTrace(level=2/0)> with
  primal = Traced<ConcreteArray([[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]], dtype=float32)>with<JaxprTrace(level=1/0)> with
    pval = (None, DeviceArray([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32))
    recipe = *
  tangent = Traced<ShapedArray(float32[7,9])>with<JaxprTrace(level=1/0)> with
    pval = (ShapedArray(float32[7,9]), *)
    recipe = LambdaBinding()].

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ionelia/pycharm-projects/grn-control/main.py", line 43, in <module>
    control(sim, 2, 9, len(sim.layers[0]))
  File "/home/ionelia/pycharm-projects/grn-control/main.py", line 23, in control
    loss, grad = jax.value_and_grad(loss_fn)(actions)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
Exception: Leaked level MainTrace(2,JVPTrace). Leaked tracer(s): [Traced<ConcreteArray([[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]], dtype=float32)>with<JVPTrace(level=2/0)> with
  primal = Traced<ConcreteArray([[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]], dtype=float32)>with<JaxprTrace(level=1/0)> with
    pval = (None, DeviceArray([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32))
    recipe = *
  tangent = Traced<ShapedArray(float32[7,9])>with<JaxprTrace(level=1/0)> with
    pval = (ShapedArray(float32[7,9]), *)
    recipe = LambdaBinding()].

Process finished with exit code 1
```

**Comment by ioneliabuzatu** [comment]
just added self.actions = action inside the simulator and leads to the error above; i dont understand where the leak comes from

**Comment by ioneliabuzatu** [comment]
the error is reproducible if set export JAX_CHECK_TRACER_LEAKS=1

**Comment by SimonDufLab** [comment]
From error log, seem that run_one_rollout is called during a grad evaluation;
https://github.com/ioneliabuzatu/grn-control/blob/5078f44fd172255da953a343cfe0eac2db5c427a/jax_simulator.py#L62-L66

As such, action is traced and can't be assigned to an object outside the scope of the grad (which is what self.actions does : it brings it out of scope to set an attribute of your main class to it).

To solve your problem either assign self.actions to actions value before or after grad. If it is not defined before grad evaluation., you can take it out as an auxiliary value from grad (has_aux=True; see https://jax.readthedocs.io/en/latest/_autosummary/jax.grad.html#jax.grad)

**Comment by ioneliabuzatu** [comment]
but if i set self.actions before or after actions, they dont influence the grad in fact i get 0 grads

**Comment by ioneliabuzatu** [comment]
```
    def loss_fn(actions, expert=classifier):
        expression_shape_trajectories_genes_cells = env.run_one_rollout(actions)
        expression_shape_cells_genes = jnp.concatenate(expression_shape_trajectories_genes_cells, axis=1).T
        return -expression_shape_cells_genes.mean()
        # return -1.0  # TODO: is loss just a scalar here?

    actions = jnp.ones(shape=(7, num_cell_types))

    for episode in range(num_episodes):
        env.actions = actions
        print("##################################################################################", episode)
        loss, grad = jax.value_and_grad(loss_fn)(actions)
        print("loss", loss)
        print(f"grad shape: {grad.shape} \n grad: {grad}")
        actions += 0.001 * -grad
```

**Comment by SimonDufLab** [comment]
Can that be because `simulate_expression_layer_wise` currently has no dependency on actions? (commented out)
https://github.com/ioneliabuzatu/grn-control/blob/5078f44fd172255da953a343cfe0eac2db5c427a/jax_simulator.py#L68-L73

**Comment by SimonDufLab** [comment]
Although, note that setting self.basal_... to actions will again cause a leak

**Comment by SimonDufLab** [comment]
Created a new branch to quickly iterate over the issue : `bug/leaks-in-grad`

Currently runnable, but it brings up a few questions/issues that would need to be addressed:

- Design choice: do we stick to dictionaries and make it consistent across the repo or keep to array and transform current dict to array before manipulation
- half_response, mean_expression etc. are not carried over now, need to be added to outputs before assigning to self
- Double check backward compatibility
- Very slow compiling of the grad; need to investigate why
- NaN quantities when taking gradient (close to 0 according to nan_to_num); need to understand why

**Comment by ioneliabuzatu** [comment]
NaN is fixed now https://github.com/ioneliabuzatu/grn-control/blob/bug/leaks-in-grad/jax_simulator.py#L80

**Comment by ioneliabuzatu** [comment]
Design choice: i removed self.x. it's ok to stick to dictionaries. i think the current version does not need revision?
